### ISSUE TITLE
imagePullCredential reference needed when using private docker images

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-is#109]
**Description:**
When deploying the helm charts, the secret "wso2creds" is created if images from wso2 docker registry is used(WSO2 credentials given). However the deployment manifest template contains no reference(imagePullCredentials) to the above mentioned secret. Therefore deployment fails when deploying the WSO2 credentials.

**Comment by Aaquiff** [comment]
Fixed in #110

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/110.
