### ISSUE TITLE
In order to change the permissions of NFS persisted volumes, sudo is used

### ISSUE THREAD

**Issue by Megala21** [wso2/kubernetes-is#11]
**Description:**
Currently in the docker file level, we change the permission of NFS persisted volumes by using sudo command. This is due the issue at [1]. However this may not work if there are security policies applied in pod and contaner level. We need to find the proper way to do this by using group id of the operating system.

[1] https://github.com/kubernetes/kubernetes/issues/2630

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:** 5.4.0, 5.4.1, 5.5.0

**OS, DB, other environment details and versions:**    Tested in google cloud.

**Steps to reproduce:**
Run the IS in kubernates engine and add some secuirty context policies to the container of IS docker image. It may give issues

**Related Issues:**
 https://github.com/kubernetes/kubernetes/issues/2630

**Comment by DilanUA** [comment]
This is fixed in later versions by managing proper user/group-ids 
both at the container level and NFS mount folder level.
