### ISSUE TITLE
Issue with duplicate imagePullSecrets name

### ISSUE THREAD

**Issue by isharac** [wso2/kubernetes-is#113]
**Description:**
If we deploying AM and IS helm charts under the same namespace.
we get below error,

Error: release wso2is failed: secrets "wso2creds" already exists

We need to use a different imagePullSecrets name
ex: wso2creds-is

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/146 and https://github.com/wso2/kubernetes-is/pull/145.
