### ISSUE TITLE
Remove 'dataSource' property from JDBC primary user store configs in user-mgt.xml

### ISSUE THREAD

**Issue by omindu** [wso2/kubernetes-is#125]
https://github.com/wso2/kubernetes-is/blob/82c8d9500bd386c3379ab7202e03a39aa749dc48/advanced/is/confs/user-mgt.xml#L217

When the above property is set for the primary user store configs, there will be a cyclic dependency during the tenant activation between the tenant's primary user store and the tenant registry.

In order to avoid the mentioned errors, the  `dataSource` property should be removed from the configs.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/150.
