### ISSUE TITLE
Remove 'deployment' directory from shared volumes

### ISSUE THREAD

**Issue by omindu** [wso2/kubernetes-is#126]
https://github.com/wso2/kubernetes-is/blob/82c8d9500bd386c3379ab7202e03a39aa749dc48/advanced/is/identity-server-deployment.yaml#L72-L73

For IS, we shouldn't have the entire deployment directory in a share volume. Only the deployment/userstores directory should be in a shared volume. As our recommended way to customize webapps is by adding them directly to the docker image, the webapps directory should not be in a shared volume as directly customizing the webapps in the shared volume can lead to a downtime of during webapp reloading

**Comment by chirangaalwis** [comment]
The refined Helm resources for WSO2 IAM deployment patterns are focused on CI/CD pipeline deployments. Hence, it has been suggested to make the option of sharing artifacts at `/home/wso2carbon/wso2is-5.8.0/repository/deployment/server` directory using a persistent storage solution, an option (disabled by default). Instead, the recommended approach is to use immutable Docker images with necessary artifacts prepackaged.

@omindu WDYT?

**Comment by omindu** [comment]
The only issue I see with this approach is the tenancy. What would be our recommendations in such cases ?

**Comment by chirangaalwis** [comment]
@omindu as per the above referenced issue (https://github.com/wso2/kubernetes-is/issues/149), we will be introducing support for persisting `/home/wso2carbon/wso2is-5.8.0/repository/tenants` directory in the expected milestone v5.8.0.4.

**Comment by omindu** [comment]
+1

**Comment by chirangaalwis** [comment]
This issue will be focused via the issue https://github.com/wso2/kubernetes-is/issues/149 in the next milestone. Hence, closing this issue.
