### ISSUE TITLE
Default path is not highlighted in the deploy script

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-is#132]
**Description:**
"Do you have a WSO2 Subscription? (Y/N)" question in the deploy script for **is-with-analytics** should be changed to "Do you have a WSO2 Subscription? (y/N)" since the default path doesn't require a subscription.

**Affected Product Version:**
IS-5.8.0

**Comment by chirangaalwis** [comment]
Since, we are planning to deprecate the Kubernetes resources for WSO2 Identity Server and promote Helm as the primary and single source of Kubernetes resource installation in the near future, I am closing this issue.
