### ISSUE TITLE
[Pattern 1] Current images are pointed to docker.wso2.com

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-is#134]
**Description:**
Current images are pointed to those available at WSO2 Private Docker Registry (`docker.wso2.com`), although it should be pointed Docker Hub images because the default execution path is open source.

**Affected Product Version:**
Kubernetes resources for WSO2 Identity Server v5.8.x

**Comment by chirangaalwis** [comment]
Since, we are planning to deprecate the Kubernetes resources for WSO2 Identity Server and promote Helm as the primary and single source of Kubernetes resource installation in the near future, I am closing this issue.
