### ISSUE TITLE
Introduce ELK stack for log aggregation and analysis for Kubernetes based WSO2 IAM pattern deployments

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#142]
**Description:**
It has been suggested to introduce the Elasticsearch, Logstash and Kibana stack, popularly known as the ELK Stack [1] for log aggregation and analysis in Helm Charts for WSO2 Identity and Access Management deployment patterns.

[1]: [ELK Stack](https://www.elastic.co/what-is/elk-stack)

**Affected Product Version:**
Helm resources for WSO2 Identity Server v5.8.x and below

**Comment by ThilinaManamgoda** [comment]
We have added Logstash as a side container to publish logs to an Elastic search Server. In order to enable this feature, a user should have an already running Elastic search server and configure the Elastic search server endpoint in the Values.yaml,.
