### ISSUE TITLE
Create "tenants" directory for shared volumes

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-is#149]
**Description:**
```
- name: shared-tenants-persistent-disk
  mountPath: /home/wso2carbon/wso2is-5.8.0/repository/tenants
```

`repository/tenants` directory should be provided as a shared volume.

**Affected Product Version:**
 Helm resources for WSO2 Identity Server v5.8.x and below

**Comment by chirangaalwis** [comment]
A related issue is https://github.com/wso2/kubernetes-is/issues/126.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/208.
