### ISSUE TITLE
Formalize naming conventions for Helm resources 

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-is#157]
**Description:**
Names provided for deployment resources should be formalized following proper naming conventions. This would make the resources more organized. Additionally, this would resolve any conflicts that may occur if multiple deployment patterns were to be set up.

**Affected Product Version:**
 Helm resources for WSO2 Identity Server v5.8.x and below

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/165.
