### ISSUE TITLE
Parameterize ingress host name

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-is#160]
**Description:**
When deploying more than one chart in a single cluster (different namespaces) the host name is same to all ingresses. This should be parameterized to allow changing the host name to differentiate between each chart.

Suggestion is to prepend the release name since it's unique. This would also require parameterize the carbon.xml to change the host name

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/161.
