### ISSUE TITLE
Update NOTES.txt to indicate instructions to access Management Console

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-is#166]
**Description:**
Once a Kubernetes cluster has been deployed, the message displayed must indicate instructions on how to access the management console.

**Affected Product Version:**
 Helm resources for WSO2 Identity Server v5.8.x and below

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/167.
