### ISSUE TITLE
[helm] Empty value is assigned to axis2 'localMemberHost' due to a missing variable

### ISSUE THREAD

**Issue by chalitha1989** [wso2/kubernetes-is#182]
**Description:**

The axix2 parameter looked like below after creating the deployment:
 <parameter name="localMemberHost"></parameter>

The reason is the variable 'docker_container_ip' 'defined in identity-server-conf-entrypoint.yaml' has no value assigned. https://github.com/wso2/kubernetes-is/blob/613ddbe0f5964b7019b1a826c477ce6fd07e82a2/advanced/helm/is-pattern-1/templates/identity-server-conf-entrypoint.yaml#L43

It should be something like this:
https://github.com/wso2/kubernetes-ei/blob/42087b538e01ab97f9b2ffc5c8afd4e3b30f388d/advanced/helm/ei-pattern-1/templates/integrator-conf-entrypoint.yaml#L44

**Suggested Labels:**
IS, Helm

**Suggested Assignees:**
NA

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
NA

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/183.
