### ISSUE TITLE
Support for latest kubernetes version

### ISSUE THREAD

**Issue by angeloimm** [wso2/kubernetes-is#195]
**Description:**
I have a ready kubernetes cluster and I'm using kubernetes 1.16. Sadly I can't downgrade. More exactly I'm using these versions:
```
[root@k8s-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
When I launch this command:
`helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace`

I get this error:
```
[root@k8s-master ~]# helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
I tried to modify the file `${KUBERNETES_IS_HOME}/advanced/is-pattern-1/templates/identity-server-ingress.yaml` in this way:
```
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
```
But I get this error:
```
[root@k8s-master ~]# helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Ingress" in version "apps/v1"]

```

Is there any way to solve this issue?

**Comment by rummyze** [comment]
The extension extensions/v1beta1 is deprecated, you should use apps/v1, however you should do this for charts ... Trying to resolve by my own

**Comment by chirangaalwis** [comment]
@angeloimm we no longer package the NFS Server Provisioner as discussed in https://github.com/wso2/kubernetes-is/issues/228,  thus this error no longer occurs when using the IAM Helm chart in Kubernetes server version `1.16`.
