### ISSUE TITLE
Bad Request Error

### ISSUE THREAD

**Issue by treenwang** [wso2/kubernetes-is#197]
**Description:**
I'm in master branch and setup wso2-is followed the guide:
https://github.com/wso2/kubernetes-is/blob/master/advanced/is-pattern-1/README.md
But when access `https://<RELEASE_NAME>/carbo`, it always return  response:
Status: `400`
Content:
`Bad Request
This combination of host and port requires TLS.`

**Comment by treenwang** [comment]
This issue was because I used the latest ingress-nginx. I changed it to 0.22.0 it works fine. Closed this ticket

**Comment by chirangaalwis** [comment]
@treenwang sorry for the late response. Please see https://github.com/wso2/kubernetes-is/issues/198 for a latest update on this topic.
