### ISSUE TITLE
[v5.10.x] NOTES.txt file needs formatting

### ISSUE THREAD

**Issue by VimukthiPerera** [wso2/kubernetes-is#217]
**Description:**

After a successful upgrade of the IS deployment pattern-1 on GKE, The following message was displayed. The formatting of the output of  `kubectl get ing -n iam` command should be fixed in [NOTES.txt](advanced/is-pattern-1/templates/NOTES.txt) file.

```
1. Obtain the external IP (`EXTERNAL-IP`) of the Ingress resources by listing down the Kubernetes Ingresses.

  kubectl get ing -n iam

    NAME                       HOSTS                  ADDRESS        PORTS     AGE
    wso2is-ingress             vimutest    <EXTERNAL-IP>  80, 443   3m

```

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/237/commits/f474638f1dc6e637025c6ce401e424c77317f098.
