### ISSUE TITLE
[v5.10.x] Specify Host on Deployment

### ISSUE THREAD

**Issue by rgauss** [wso2/kubernetes-is#222]
**Description:**
As a developer and/or administrator I'd like to be able to specify the **host** for my deployment so that I don't have to require every user accessing the environment to update their `/etc/hosts` file with the Kubernetes release name.

**Affected Product Version:**
5.10

**OS, DB, other environment details and versions:**    
Kubernetes

**Steps to reproduce:**
N/A - not a bug

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/235. Thus, closing.
