### ISSUE TITLE
Wrong path in identity-server-deployment.yaml

### ISSUE THREAD

**Issue by angeloimm** [wso2/kubernetes-is#239]
In the file https://github.com/wso2/kubernetes-is/blob/master/advanced/is-pattern-1/templates/is/identity-server-deployment.yaml we see a wrong log path location when central logging is enabled.
We have:
```
{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          mountPath: /home/wso2carbon/wso2is-5.8.0/repository/logs/

```
I thin it should be
```
{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          mountPath: /home/wso2carbon/wso2is-5.10.0/repository/logs/
```
Am I correct?

**Comment by chirangaalwis** [comment]
Related issue: https://github.com/wso2/kubernetes-is/issues/234
