### ISSUE TITLE
[v5.10.x] Verify Logstash default plugins 

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-is#245]
**Description:**
It is required to verify whether the plugins that are used for centralized logging, `logstash-codec-multiline` & `logstash-filter-grok` come under default plugins for Logstash. If those are bundled with Logstatsh by default, we can remove the Logstatsh plugin installation step. 

**Affected Product Version:**
5.10.0

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/246/commits/d8b96f7b116a71a32ebbb14b6229a59dd96cef29.
