### ISSUE TITLE
Validate support for Kubernetes version 1.17

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-is#265]
**Description:**
It is required to validate the Identity server Helm resource against Kubernetes version `1.17`.

**Affected Product Version:**
All the versions.

**Comment by chirangaalwis** [comment]
@ThilinaManamgoda this is already done. Please check the release [notes](https://github.com/wso2/kubernetes-is/releases/tag/v5.10.0.2).

**Comment by ThilinaManamgoda** [comment]
This task has been done already.
