### ISSUE TITLE
[5.11.0] Introduce WSO2 IAM Helm Chart For Production Grade Deployment Pattern

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#266]
**Description:**
It is required to cover $subject (for advanced details please refer to official [documentation](https://is.docs.wso2.com/en/latest/setup/deployment-guide/#deployment-patterns)) for production grade Kubernetes based deployments.

**Comment by okhuz** [comment]
Hello, is this "Production Grade Deployment Pattern" will be like pattern 2 in 5.9.x?

**Comment by chirangaalwis** [comment]
> Hello, is this "Production Grade Deployment Pattern" will be like pattern 2 in 5.9.x?

@okhuz no. This will be an Identity Server (IS) deployment with high availability with no IS Analytics support (in other terms, a pattern 1 deployment).

**Comment by chirangaalwis** [comment]
Fixed.
