### ISSUE TITLE
[v5.11.x] Image not define in the is-pattern-1 template

### ISSUE THREAD

**Issue by RidmiR** [wso2/kubernetes-is#288]
**Description:**
As described in the issue subject in current 5.11.x version there is an issue observing when doing the helm template. Observing 
below issue :

> Error: template: is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml:77:4: executing "is-pattern-1/templates/is/wso2is-pattern-1-identity-server-statefulset.yaml" at <include "image" (dict "Values" .Values "deployment" .Values.wso2.deployment.wso2is)>: error calling include: template: no template "image" associated with template "gotpl

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/289.
