### ISSUE TITLE
Add Helm Charts for Identity server with analytics 5.6.0 & IS 5.6.0

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-is#43]
**Description:**
Helm charts should be created for the deployment of clustered Identity Server with analytics.
Helm charts should be created for the deployment of clustered Identity Server.
**Suggested Labels:**
Type/NewFeature

**Affected Product Version:**
WSO2 Identity server 5.6.x

**Comment by chirangaalwis** [comment]
This is fixed in https://github.com/wso2/kubernetes-is/pull/44.
