### ISSUE TITLE
Support for databases other than MySQL

### ISSUE THREAD

**Issue by kasunbg** [wso2/kubernetes-is#5]
**Description:**
Even though MySQL is a good first choice, but Oracle, MSSQL, and Postgres has just as much usage as MySQL (probably more). So, I think it is best if we can support multiple RDBMS databases.

Some of these has commercial licenses. So, I think it is good if we can generalize the wso2is Dockerfile to support any RDBMS rather than hard-binding to MySQL.

Does this make sense?

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by chirangaalwis** [comment]
@kasunbg we are prepackaging the MySQL Connector in Docker images as we are using MySQL for deploying the product databases in evaluation resources such as, Docker Compose.

But in the case of using other RDBMSs (in production grade installation artifacts such as, Kubernetes), the current recommended approach is to use a volume mount to provide the necessary artifacts (e.g. relevant database connector) into the product container (e.g. refer the instructions provided in Kubernetes resource README.md [documentation](https://github.com/wso2/kubernetes-is#how-to-update-configurations) for passing additional configuration files, binaries and etc.)

**Comment by DilanUA** [comment]
Marking "resolved" based on above comment.
