### ISSUE TITLE
Volume for mysql?

### ISSUE THREAD

**Issue by malcolmm83** [wso2/kubernetes-is#60]
**Description:**

The instructions seem to be missing a step for creation of the persistent volume to match the claim for mysql.

**Suggested Labels:**

mysql, persistentvolume
**Suggested Assignees:**

The volume for msql should probably be created at the same time as the 2 for IS
**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by DilanUA** [comment]
Closing based on above comment.
