### ISSUE TITLE
Formatting issue in the info log messages of deploy.sh script

### ISSUE THREAD

**Issue by ajanthan** [wso2/kubernetes-is#62]
**Description:**

While running the deploy.sh script the info logs have '-e' in each message.

namespace "wso2" created
serviceaccount "wso2svc-account" created
Context "minikube" modified.
secret "wso2creds" created
role.rbac.authorization.k8s.io "endpoints-reader-role" created
rolebinding.rbac.authorization.k8s.io "wso2-endpoints-reader-role-binding" created
-e Creating Kubernetes ConfigMaps...
configmap "identity-server-conf" created
configmap "identity-server-conf-axis2" created
configmap "identity-server-conf-datasources" created
configmap "identity-server-conf-identity" created
configmap "mysql-dbscripts" created
-e Deploying the Kubernetes Services...
service "wso2is-rdbms-service" created
service "wso2is-service" created
-e Deploying WSO2 Identity Server Databases using MySQL...
deployment.apps "wso2is-mysql-deployment" created
-e Creating persistent volumes and volume claims...
persistentvolumeclaim "is-shared-deployment-volume-claim" created
persistentvolumeclaim "is-shared-tenants-volume-claim" created
persistentvolume "wso2is-shared-deployment-pv" created
persistentvolume "wso2is-shared-tenants-pv" created
persistentvolumeclaim "wso2is-rdbms-volume-claim" created
persistentvolume "wso2is-mysql-pv" created
-e Deploying WSO2 Identity Server...
deployment.apps "wso2is-deployment" created
-e Deploying Kubernetes Ingresses...
ingress.extensions "wso2is-ingress" created
-e Finished
-e To access the WSO2 Identity Server management console, try https://wso2is/carbon in your browser.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chirangaalwis** [comment]
@ajanthan since, we are planning to deprecate the Kubernetes resources for WSO2 Identity and Access Management deployment patterns and promote Helm as the primary and single source of Kubernetes resource installation in the near future, I am closing this issue.

Please feel free to share your thoughts and suggestions and if necessary, re-open this issue.
