### ISSUE TITLE
Refine support for introducing additional configuration changes and artifacts in version 5.5.x deployments

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#67]
**Description:**
Recently, WSO2 Identity Server 5.5.x Docker resources were refined to support the introduction of additional configuration changes and artifacts.

In order to introduce additional configuration changes, a single, predefined folder location `/home/wso2carbon/wso2-config-volume` is to be introduced. Further, since Kubernetes supports mounting of ConfigMaps while being able to maintain a hierarchical folder structure, it was decided to remove the multiple ConfigMap volume mount points defined in earlier entrypoint scripts.

Plus, an additional, predefined folder location `/home/wso2carbon/wso2-artifact-volume` is to be introduced to support mounting additional binaries and other artifacts.

Thus, the existing Kubernetes resources need to be refined to support the new folder structure.

**Affected Product Version:**
WSO2 Identity Server 5.5.x, WSO2 Identity Server Analytics 5.5.x

**Related Issues:**
https://github.com/wso2/docker-is/issues/80

**Comment by DilanUA** [comment]
Corresponding support for this feature @docker-level is already provided by PR: https://github.com/wso2/docker-is/pull/76. Only the documentation @ k8s level is missing at the moment.

**Comment by chirangaalwis** [comment]
@DilanUA The relevant documentation for the discussed matter at Kubernetes resource level can be found from [1].

[1]: [README documentation](https://github.com/wso2/kubernetes-is/blob/v5.5.x/README.md)

Hence, closing the issue.
