### ISSUE TITLE
Refine support for introducing additional configuration changes and artifacts in version 5.6.x deployments

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#68]
**Description:**
Recently, WSO2 Identity Server 5.6.x Docker resources were refined to support the introduction of additional configuration changes and artifacts.

In order to introduce additional configuration changes, a single, predefined folder location `/home/wso2carbon/wso2-config-volume` is to be introduced. Further, since Kubernetes supports mounting of ConfigMaps while being able to maintain a hierarchical folder structure, it was decided to remove the multiple ConfigMap volume mount points defined in earlier entrypoint scripts.

Plus, an additional, predefined folder location `/home/wso2carbon/wso2-artifact-volume` is to be introduced to support mounting additional binaries and other artifacts.

Thus, the existing Kubernetes resources need to be refined to support the new folder structure.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
WSO2 Identity Server 5.6.x, WSO2 Identity Server Analytics 5.6.x

**Related Issues:**
https://github.com/wso2/docker-is/issues/81

**Comment by DilanUA** [comment]
Resolved by release: https://github.com/wso2/kubernetes-is/releases/tag/v5.6.0.1
