### ISSUE TITLE
Provide a simpler approach for customers to setup WSO2 IS

### ISSUE THREAD

**Issue by NishikaDeSilva** [wso2/kubernetes-is#83]
**Description:**
Setting up WSO2 Identity server deployment in Kubernetes environment can be rather difficult. Thus it is better to have much simpler way of setting up things for an unexperienced user in a basic level. 

**Affected Product Version:**
5.7.x

**Comment by nparks-kenzan** [comment]
To provide a specific suggestion to @NishikaDeSilva issue...

When I read the volume set-up my first thoughts where:

1. This screams `StatefulSet`

1. Whey there is no helm pre-install hook via a k8 job to run some additional filesystem set-up within the PVC?


If your K8 environment can't do StatefulSets than you have a busted K8 environment. 
There are many clustered solutions (like KeyCloak cough cough) that use StatefulSets. So, when I read these steps I get the sense there is one more iteration of refinement to make this a top level helm chart hosted along side the other charts in github.com/helm.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/101.
